import type Item from "~/server/tyoes/itemType";
export const items: Item[] = [
    {
        id: "1",
        name: "Mystic Orb",
        price: 150,
        description: "A glowing orb that reveals hidden messages.",
        image: "https://i.imgur.com/mysticOrb.png",
    },
    {
        id: "2",
        name: "Echo Pendant",
        price: 200,
        description: "A pendant that echoes distant sounds and voices.",
        image: "https://i.imgur.com/echoPendant.png",
    },
    {
        id: "3",
        name: "Timekeeper's Watch",
        price: 250,
        description: "A watch that can manipulate small moments in time.",
        image: "https://i.imgur.com/timekeepersWatch.png",
    },
    {
        id: "4",
        name: "Invisibility Cloak",
        price: 300,
        description: "A cloak that renders the wearer invisible for a short period.",
        image: "https://i.imgur.com/invisibilityCloak.png",
    },
    {
        id: "5",
        name: "Sky Boots",
        price: 350,
        description: "Boots that allow the wearer to walk on air.",
        image: "https://i.imgur.com/skyBoots.png",
    },
    {
        id: "6",
        name: "Phoenix Feather Quill",
        price: 180,
        description: "A magical quill that never runs out of ink.",
        image: "https://i.imgur.com/phoenixFeatherQuill.png",
    },
    {
        id: "7",
        name: "Shadow Lantern",
        price: 220,
        description: "A lantern that illuminates hidden truths in the dark.",
        image: "https://i.imgur.com/shadowLantern.png",
    },
    {
        id: "8",
        name: "Elixir of Wisdom",
        price: 275,
        description: "A rare elixir that boosts intelligence temporarily.",
        image: "https://i.imgur.com/elixirOfWisdom.png",
    },
    {
        id: "9",
        name: "Mirror of the Past",
        price: 320,
        description: "A mirror that shows glimpses of the past.",
        image: "https://i.imgur.com/mirrorOfThePast.png",
    },
    {
        id: "10",
        name: "Starlight Compass",
        price: 400,
        description: "A compass that points towards your heart's true desire.",
        image: "https://i.imgur.com/starlightCompass.png",
    },
    {
        id: "11",
        name: "Galeforce Ring",
        price: 425,
        description: "A ring that can summon powerful gusts of wind.",
        image: "https://i.imgur.com/galeforceRing.png",
    }
];
